### Análise Exploratória das Métricas Globais de Conectividade

Este notebook apresenta a análise exploratória das métricas globais de conectividade funcional cerebral extraídas a partir de sinais de EEG em estado de repouso.

O objetivo desta etapa é:
- caracterizar estatisticamente as métricas globais,
- investigar diferenças entre condições experimentais (EO vs EC),
- fornecer subsídios para as etapas posteriores de redução de dimensionalidade e aprendizado de máquina.

### Import e carregamento

In [1]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

In [ ]:
# Carrega dataset final
df = pd.read_parquet("../data/processed/dataset_features.parquet")

df.shape

(165, 393)

### Seleção das métricas globais

“As métricas globais representam propriedades agregadas da rede funcional cerebral, independententes de regiões específicas, refletindo o nível geral de integração e variabilidade da conectividade.”

In [3]:
GLOBAL_FEATURES = [
    "global_efficiency",
    "edges_mean",
    "edges_std",
    "edges_cv"
]

id_cols = ["subject_id", "condition"]

df_global = df[id_cols + GLOBAL_FEATURES]

df_global.head()

   subject_id condition  global_efficiency  edges_mean  edges_std  edges_cv
0  sub-010060        EO                1.0      1830.0        0.0       0.0
1  sub-010061        EC                1.0      1770.0        0.0       0.0
2  sub-010061        EO                1.0      1770.0        0.0       0.0
3  sub-010062        EC                1.0      1653.0        0.0       0.0
4  sub-010062        EO                1.0      1770.0        0.0       0.0

In [4]:
df_global[GLOBAL_FEATURES].describe()

       global_efficiency   edges_mean  edges_std  edges_cv
count              165.0   165.000000      165.0     165.0
mean                 1.0  1768.539394        0.0       0.0
std                  0.0    69.854771        0.0       0.0
min                  1.0  1540.000000        0.0       0.0
25%                  1.0  1711.000000        0.0       0.0
50%                  1.0  1770.000000        0.0       0.0
75%                  1.0  1830.000000        0.0       0.0
max                  1.0  1830.000000        0.0       0.0

In [5]:
df_global.groupby("condition")[GLOBAL_FEATURES].describe()

          global_efficiency                                    edges_mean  \
                      count mean  std  min  25%  50%  75%  max      count
condition
E0                      1.0  1.0  NaN  1.0  1.0  1.0  1.0  1.0        1.0
EC                     82.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0       82.0
EO                     82.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0       82.0

                        ... edges_std      edges_cv                           \
                  mean  ...       75%  max    count mean  std  min  25%  50%
condition               ...
E0         1770.000000  ...       0.0  0.0      1.0  0.0  NaN  0.0  0.0  0.0
EC         1766.451220  ...       0.0  0.0     82.0  0.0  0.0  0.0  0.0  0.0
EO         1770.609756  ...       0.0  0.0     82.0  0.0  0.0  0.0  0.0  0.0


           75%  max
condition
E0         0.0  0.0
EC         0.0  0.0
EO         0.0  0.0

[3 rows x 32 columns]

### Boxplots EO vs EC

Eficiência global

In [8]:
fig = px.box(
    df_global,
    x="condition",
    y="global_efficiency",
    color="condition",
    points="all",
    title="Eficiência Global da Rede por Condição Experimental"
)
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Número médio de arestas

In [7]:
fig = px.box(
    df_global,
    x="condition",
    y="edges_mean",
    color="condition",
    points="all",
    title="Número Médio de Arestas por Condição"
)
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed